tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-container-lowest": "#ffffff",
                "on-error-container": "#93000a",
                "error": "#ba1a1a",
                "primary-fixed-dim": "#ffb4a9",
                "surface-tint": "#ac3327",
                "inverse-primary": "#ffb4a9",
                "secondary-container": "#c7edc1",
                "secondary-fixed-dim": "#abd0a6",
                "on-secondary-fixed": "#022107",
                "on-primary": "#ffffff",
                "outline": "#8c716d",
                "inverse-on-surface": "#f5f0e4",
                "on-tertiary-fixed-variant": "#574500",
                "background": "#fef9ed",
                "primary-fixed": "#ffdad5",
                "tertiary": "#735c00",
                "primary": "#6b0001",
                "surface-dim": "#dedace",
                "on-surface": "#1d1c15",
                "surface-container-high": "#ede8dc",
                "surface-container": "#f2ede2",
                "surface-variant": "#e7e2d6",
                "outline-variant": "#e0bfba",
                "secondary": "#456644",
                "on-surface-variant": "#58413e",
                "on-tertiary-fixed": "#241a00",
                "on-tertiary": "#ffffff",
                "tertiary-fixed": "#ffe088",
                "surface-container-highest": "#e7e2d6",
                "surface-bright": "#fef9ed",
                "tertiary-container": "#cca730",
                "on-primary-container": "#ff9d8e",
                "error-container": "#ffdad6",
                "on-background": "#1d1c15",
                "on-secondary": "#ffffff",
                "on-tertiary-container": "#4f3d00",
                "on-primary-fixed": "#410000",
                "on-secondary-container": "#4b6c4a",
                "on-error": "#ffffff",
                "surface-container-low": "#f8f3e7",
                "surface": "#fef9ed",
                "on-primary-fixed-variant": "#8a1b12",
                "on-secondary-fixed-variant": "#2e4e2e",
                "inverse-surface": "#323029",
                "primary-container": "#8c1c13",
                "secondary-fixed": "#c7edc1",
                "tertiary-fixed-dim": "#e9c349"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "1.5rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Inter"],
                "label": ["Inter"]
            }
        },
    },
};
